### ISSUE TITLE
Error with Makefile

### ISSUE THREAD

**Issue by randomonium8** [jdah/tetris-os#1]
i386-elf-as -o src/stage0.o -c src/stage0.S  
make: i386-elf-as: No such file or directory
make: *** [Makefile:41: src/stage0.o] Error 127

**Comment by ajh123** [comment]
that means you may not have ```i386-elf-as``` installed
try ```i386-elf-as -v``` on your command line and it should print it's version out

**Comment by atmeh** [comment]
On macOS with homebrew you can install it
`brew tap nativeos/i386-elf-toolchain`
`brew install i386-elf-binutils i386-elf-gcc`

**Comment by a7madjg** [comment]
does anyone know where do i get the package from on Arch Linux? can't seem to find it anywhere

**Comment by marchellodev** [comment]
For linux, you can use https://drive.google.com/file/d/0Bw6lG3Ej2746STJaM2dNbC05elE/view?usp=sharing (From https://wiki.osdev.org/GCC_Cross-Compiler). Just add bin folder to your path.

**Comment by a7madjg** [comment]
Hey, tried copying all the executables in the /bin folder in that tarball you sent me to my /usr/bin, but i get this error:
```
i386-elf-ld -o ./bin/bootsect.bin src/stage0.o -Ttext 0x7C00 --oformat=binary
i386-elf-gcc -o src/font.o -c src/font.c  -m32 -std=c11 -O2 -g -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wno-pointer-arith -Wno-unused-parameter -nostdlib -nostdinc -ffreestanding -fno-pie -fno-stack-protector -fno-builtin-function -fno-builtin
i386-elf-gcc: error trying to exec 'cc1': execvp: No such file or directory
make: *** [Makefile:38: src/font.o] Error 1
```

**Comment by marchellodev** [comment]
It seems like this file is located in `386-elf-7.5.0-Linux-x86_64/libexec/gcc/i386-elf/7.5.0/cc1`

**Comment by CoolingJam** [comment]
Im trying to run this on ubuntu and im running in same problem.
make: i386-elf-as: No such file or directory

**Comment by PoseidonCoder** [comment]
![image](https://user-images.githubusercontent.com/34260118/115310069-0cc30700-a122-11eb-92d5-7bc8ddf77a23.png)
I have it installed but the makefile doesn't detect it

**Comment by marchellodev** [comment]
@CoolingJam It seems like a shared library located in the bin folder. Why not just add the whole bin folder to your path? (`PATH=$PATH:/path/to/bin/folder`)

**Comment by PoseidonCoder** [comment]
I had the same error but after installing https://newos.org/toolchains/i386-elf-7.5.0-Linux-x86_64.tar.xz and adding it to my path. I added executable permissions to the Makefile and executed it by `./Makefile`

**Comment by PoseidonCoder** [comment]
I'll share the shell script that will install it *later*.

**Comment by a7madjg** [comment]
> @CoolingJam It seems like a shared library located in the bin folder. Why not just add the whole bin folder to your path? (`PATH=$PATH:/path/to/bin/folder`)
Hey, tried doing this and got this error message:
```
i386-elf-ld -o ./bin/bootsect.bin src/stage0.o -Ttext 0x7C00 --oformat=binary
i386-elf-ld -o ./bin/kernel.bin src/font.o src/fpu.o src/idt.o src/irq.o src/isr.o src/keyboard.o src/main.o src/math.o src/music.o src/screen.o src/sound.o src/speaker.o src/system.o src/timer.o src/start.o  -Tsrc/link.ld
dd if=/dev/zero of=boot.iso bs=512 count=2880
make: dd: No such file or directory
make: *** [Makefile:51: iso] Error 127
```

**Comment by a7madjg** [comment]
> I had the same error but after installing https://newos.org/toolchains/i386-elf-7.5.0-Linux-x86_64.tar.xz and adding it to my path. I added executable permissions to the Makefile and executed it by `./Makefile`
Thank you so much

**Comment by PoseidonCoder** [comment]
Here's the shell script:
https://gist.github.com/PoseidonCoder/03a93689546a0e3fa57570f23f92398c
(hopefully this helps)

**Comment by marchellodev** [comment]
@PoseidonCoder Did you manage to get it actually working? I am facing #2 for some reason

**Comment by allaeddineomc** [comment]
i forked the repo and fixed building on linux but i couldn't create a pull request you can get the linux make file from my fork 
it's tested on arch linux

**Comment by allaeddineomc** [comment]
i also published a ready to run iso as a release

**Comment by PoseidonCoder** [comment]
nice

**Comment by jdah** [comment]
This is all recorded in the README now and it explicitly specifies that you need a cross compiler. Thanks for all the help with that in here everyone :)
