### ISSUE TITLE
Failed to reset SB16: 255

### ISSUE THREAD

**Issue by AcaiBerii** [jdah/tetris-os#18]
Running on QEMU-System x86/64.
Windows 10 x64
Should I choose another QEMU system?

**Comment by takaswie** [comment]
You need to indicate option for sb16 hardware emulation to QEMU process:

```
$ qemu-system-x86_64 ... -device sb16 ...
```

Regards

**Comment by jdah** [comment]
@AcaiBerii what's the exact command you're using to run? and @takaswie is correct, you do need the SB16 enabled if `ENABLE_MUSIC` is on (which it is by default).

**Comment by AcaiBerii** [comment]
My current command:
`qemu-system-x86_64 "C:\Users\****\Downloads\boot.iso" -m 2G`

**Comment by jdah** [comment]
Yeah you need to enable the SB16 with at least `-device SB16` and maybe more configuration (see the README) to get the sound to come through.

**Comment by jdah** [comment]
Closing this issue, looks like it is just due to missing SB16.
