### ISSUE TITLE
Guideline Tetris?

### ISSUE THREAD

**Issue by bouncepaw** [jdah/tetris-os#21]
Is this a Guideline-compatible Tetris? Judging by the colors of minos on the screenshot, it must be,. If it's not, please make it a Guideline Tetris to improve playability.

https://tetris.wiki/Tetris_Guideline

**Comment by jdah** [comment]
It isn't guideline compatible, but I also do not plan on making it so - the Tetris company is already quite overzealous with trademark/copyright protection and I would rather not make this project more vulnerable to a takedown. I appreciate the input though.
