### ISSUE TITLE
Sound is broken on ALSA and Pulseaudio

### ISSUE THREAD

**Issue by xerz-one** [jdah/tetris-os#25]
Despite the recent buffer change to `#define BUFFER_MS 40` and other suggested solutions, audio under the ALSA and Pulseaudio drivers is broken on my Arch Linux setup, using:

- QEMU 5.2.0
- ALSA 5.11.15
- PulseAudio 14.2
- GNOME 40.

As a workaround, using the SDL audio driver suffices to make it no longer a problem -- this suggests SDL is working around issues the other QEMU drivers can't on their own. The following command runs Tetris OS smoothly:

```
qemu-system-i386 -display sdl -drive format=raw,file=boot.iso -d cpu_reset -monitor stdio -audiodev sdl,id=sdl,out.frequency=48000,out.channels=2,out.format=s32 -device sb16,audiodev=sdl
```

**Comment by xerz-one** [comment]
(sidenote.: adding `-accel kvm` works, so it can't harm anyone to do that as well)

**Comment by jdah** [comment]
Thanks for the workaround! I'll note this in the README.

**Comment by jdah** [comment]
Noted in the REAEDME :)

**Comment by xerz-one** [comment]
Not sure this ticket should be closed? But glad to know!

**Comment by jdah** [comment]
@xerz-one Ah, maybe, but that depends on what you mean by audio being "broken" - I know QEMU has audio issues which I'm happy to offer workarounds for but if there's nothing that can really be done from an implementation side the I'm not sure what else to do.
