### ISSUE TITLE
Error Messages: "PCI System Error" and "FAILED TO RESET"

### ISSUE THREAD

**Issue by Benjamin-6848** [jdah/tetris-os#27]
I am testing this on an real machine (an older laptop - desinged for windows xp) ...

The laptop successfully loaded the boot-image, but i am getting two errors: 
First, it shows the "Tetris Time" message, but soon it shows an error-message that says: 
"PCI System Error on Bus/Device/Function 0000h", 
than the message disappeares, the graphics-display-mode loads and the custom Tetris-Font shows the following error-message: 
"FAILED TO RESET SB16: 225". 

I am do not know, what i did wrong, or what didn't worked ...

Kind regards
Benjamin

**Comment by jdah** [comment]
Do you hav an SB16 in your laptop? I'm guessing probably not. If you're building for real hardware without an SB16 you need to disable the driver by removing `#define ENABLE_MUSIC` from `main.c`.

**Comment by Benjamin-6848** [comment]
> 
> 
> Do you have an SB16 in your laptop? I'm guessing probably not. If you're building for real hardware without an SB16 you need to disable the driver by removing `#define ENABLE_MUSIC` from `main.c`.

The code dosen't contain an Variable or Constant named `ENABLE_MUSIC` ...

**Comment by jdah** [comment]
The code has been updated since :) it now automatically disables the SB16 code if it can't be found, so this should work just fine.

**Comment by Benjamin-6848** [comment]
> 
> 
> The code has been updated since :) it now automatically disables the SB16 code if it can't be found, so this should work just fine.

Thank you for your quick answers and sorry that my answers are taking so much time! 

I have now successfully used the updated release from 28. April 2021. 
It is working fine! Thank you for your help and your hard work! It is great!
