### ISSUE TITLE
Publish no-audio builds

### ISSUE THREAD

**Issue by jonahsnider** [jdah/tetris-os#29]
It looks like having audio enabled in the build can cause issues on some emulators/PCs (#20). Could an official build with audio disabled be included in releases?

**Comment by zment4** [comment]
Not an "official" build but I did make a release on a dynamically disabled SB16 on my fork https://github.com/zment4/tetris-os/tree/chs_dynSB16v1

**Comment by jdah** [comment]
No longer necessary, audio now dynamically disables :)

**Comment by jonahsnider** [comment]
Using the latest build still gives me the bug seen in #20. Maybe the dynamic audio code is flawed? Or maybe #20 is unrelated to audio entirely.

**Comment by zment4** [comment]
> Using the latest build still gives me the bug seen in #20. Maybe the dynamic audio code is flawed? Or maybe #20 is unrelated to audio entirely.

Can you confirm conditionally compiling music out of the build results in that behaviour? Anyway, both are totally possible scenarios. I can try to test things and trigger that behaviour myself today. I'll report back if I find anything, maybe re-opening this or opening a new issue ends up being warranted

**Comment by zment4** [comment]
Went through the latest changes, and the dynamic disabling should work just fine. I'll test it with other emulators like VirtualBox etc. to make sure though. Hm. I wonder if you could just disable all of the sound backends to mimic undefining #ENABLE_MUSIC?
