### ISSUE TITLE
How do i make the iso bootable ?

### ISSUE THREAD

**Issue by UserUNP** [jdah/tetris-os#37]
i wanted to try it on real hardware, tho i don't know how to make it bootable, cause i can't open the .iso using WinRar, for some reason it says its corrupted/damaged.

**Comment by jdah** [comment]
Don't open it with WinRAR, it's already marked bootable by the `0xAA55` at the end of the boot sector. There's no filesystem on the ISO so nothing can open it except a hex editor really.

**Comment by bence98** [comment]
@jdah You should consider naming it `boot.img` instead, as that reflects the contents better (it is a raw disk image, and not an ISO9660 partition).
