### ISSUE TITLE
I cannot get Qemu up and running?

### ISSUE THREAD

**Issue by Jaantheman** [jdah/tetris-os#38]
I tried to put this in in CMD terminal but got this:

"Invalid parameter 'pulseaudio'"

Maybe its the terminal I am using. IDK!

**Comment by DefunctLizard** [comment]
It's definitely not the terminal emulator you're using, it's probably the pulseaudio/qemu libraries you have installed.

I had this problem when I first ran it and I just ran it with the SDL backend and it worked:
```
qemu-system-i386 -display sdl -drive format=raw,file=boot.iso -d cpu_reset -monitor stdio -audiodev sdl,id=sdl,out.frequency=48000,out.channels=2,out.format=s32 -device sb16,audiodev=sdl
```

**Comment by jdah** [comment]
Yep, your system just doesn't have pulseaudio.
