### ISSUE TITLE
Random tetromino sequence

### ISSUE THREAD

**Issue by philo23** [jdah/tetris-os#41]
This is really fun little project, but one thing I couldn't help notice in the video is that the pieces generated seem to be completely random and sometimes you end up with the same one quite often.

My understanding is that, at least with newer games, the next 7 pieces are generated as if pulled from a bag. That way you're way less likely to get the same tetromino over and over again: https://tetris.fandom.com/wiki/Random_Generator

I might have a play about adding it but I probably won't get around to submitting anything serious. It seems like the next/first piece is picked in the `spawn` function of main.c

It's only a minor nitpick but I figured I'd submit an issue just in case anyone else feels up to doing it.

**Comment by VFDan** [comment]
This mechanic is the one I know, so it's a bit confusing when I get four S pieces in a row :P

**Comment by 0x0015** [comment]
I think this is supposed to be accurate to the original tetris game (on the nes) where it is completely random(see https://youtu.be/FaILnmUYS_U?t=877 or 14:37 in the explanation video).

**Comment by jdah** [comment]
Thanks for the suggestion, but I'll keep it as is - just trying to emulate the oldest/most basic version of Tetris I can while trying to keep a healthy distance from more specific game mechanics in the name of copyright 👀

**Comment by zment4** [comment]
There might become a time in the future where the name of the project has to be changed to "BlockOS". It's not so much the game mechanics (the mechanics themselves aren't really copyrightabla nor trademarkable) as the name itself. And Tetris trademark holder's are as rabid as Nintendo in protecting their trademarks. 

In case there will be a DMCA takedown request in the future, a simple rename should do (especially if you keep your distance from specific mechanics, like you said here you would rather do - even though they aren't copyrightable/trademarkable, it can be shown as intent). 

All that said, IANAL, I'm probably talking out of my hat.
