### ISSUE TITLE
failed to reset SB16: 255 and issue using original command to start

### ISSUE THREAD

**Issue by coreybruce** [jdah/tetris-os#43]
I am unable to boot Tetris as I get stuck on this screen on Manjaro

![image](https://user-images.githubusercontent.com/8393780/116040624-9b4e0000-a6af-11eb-891d-2da8ee29f382.png)

I had to use this version of the launch command 
``qemu-system-i386 -drive format=raw,file=boot.iso```

As I get this error saying the pulseaudio argument doesn't exist

```
[corey@corey-laptop Downloads]$ qemu-system-i386 -drive format=raw,file=boot.iso -d cpu_reset -monitor stdio -device sb16 -audiodev pulseaudio,id=pulseaudio,out.frequency=48000,out.channels=2,out.format=s32
qemu-system-i386: -audiodev pulseaudio,id=pulseaudio,out.frequency=48000,out.channels=2,out.format=s32: Invalid parameter 'pulseaudio'
```

**Comment by jdah** [comment]
Have you tried with the SDL backend like the README suggests?

**Comment by coreybruce** [comment]
Not yet and should I ?

**Comment by jdah** [comment]
Yes, it says in the README to try it if sound is still broken with the pulseaudio backend.

**Comment by coreybruce** [comment]
Sorry for missing that part, it works now thanks!

And thanks for the hard work, loved the video.
