### ISSUE TITLE
ISO def in Makefile

### ISSUE THREAD

**Issue by alve1801** [jdah/tetris-os#47]
Minor issue: in the Makefile, ISO is defined to equal "boot.iso", I assume to define which file the image gets assembled into. However, that definition is not used, and "boot.iso" is instead hardcoded in the commands.
Should be something like this: [Makefile.txt](https://github.com/jdah/tetris-os/files/6380818/Makefile.txt)

**Comment by jdah** [comment]
Has since been fixed, thanks for filing the issue.

**Comment by alve1801** [comment]
My issue was rather that lines 59 and 60 in the Makefile (the `dd` commands) have the argument `of=boot.img` instead of `of=$(IMG)`

**Comment by jdah** [comment]
Whoops, that's also been fixed now :)
