### ISSUE TITLE
Running on WSL

### ISSUE THREAD

**Issue by MadDogofShimano** [jdah/tetris-os#48]
Since the inclusion of WSLg in the Windows Insider builds past 21362, I've tested out the OS with the new GUI. Can confirm it is working without sound. I will see what I can do about finding a fix for the error audio.

![WSLG](https://user-images.githubusercontent.com/59043410/116169269-37303980-a6b9-11eb-8f36-811a1999d0ee.PNG)

**Comment by zment4** [comment]
QEMU works in Windows with native builds, no need to install WSL for that (just download the official release and run with `qemu-system-i386 -display sdl -drive format=raw,file=boot.bin -audiodev id=dsound,driver=dsound -device sb16,audiodev=dsound` or with `qemu-system-i386 -display sdl -drive format=raw,file=boot.bin -audiodev id=dsound,driver=dsound,out.fixed-settings=on,out.frequency=22050,out.buffer-length=80000,timer-period=100 -device sb16,audiodev=dsound` if you are having performance issues. Fiddling with frequency, buffer-length an timer-period should help to get solid audio from it. 

I also have written some instructions on getting the thing to compile in Windows without needing WSL #24 in case you want to build it yourself. However, I have also provided on my fork a more compatible binary build, but I don't think you'll need it unless you are going to try to run on real hardware.

Oh and nothing wrong with WSL, just thought I'd mention that that's not the only option. And I actually think you might have better luck with getting sound working with native Windows QEMU.

**Comment by MadDogofShimano** [comment]
That's true. However I just like fiddling around with WSL and want to see if I can get it working. But thanks for the additional info on compiling natively. If this doesn't work out then I may move to that.
