### ISSUE TITLE
failed to load SB15: 255

### ISSUE THREAD

**Issue by tarneaux** [jdah/tetris-os#49]
If I run  it with QEMU or just use the disk image to boot, I get the error failed to load SB15: 255.

**Comment by jdah** [comment]
Please read the README. Make sure that the SB16 is enabled on QEMU, try with the SDL backend if it still doesn't work, or build the image with sound disabled.

**Comment by tarneaux** [comment]
I can't run SDL, it's no more available in QEMU. This error also pops up when I build with sound off.
