### ISSUE TITLE
Working on a Dell Vostro 1520 (without sound_init() )

### ISSUE THREAD

**Issue by EpicLPer** [jdah/tetris-os#54]
Confirmed working on real hardware (after removing sound_init() ), a Dell Vostro 1520 👍 :)

https://twitter.com/EpicLPer/status/1387473302118076422

**Comment by parkerlreed** [comment]
This would also work in the real hardware thread :)

**Comment by EpicLPer** [comment]
Whoops, didn't know there exists one ^^" Sorry!
