### ISSUE TITLE
Brew install error (Mac mini M1): clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by MarcoDotIO** [jdah/tetris-os#62]
While yes it's not necessarily an issue with Tetris OS, I wanted to see if I'm the only one running into this issue when trying to install i386 elf GCC on an M1 Mac. Probably by the look of things, I would need to know an alternative way of installing this toolchain, so let me know my options. Also here is the error code output I'm getting:

==> Installing i386-elf-gcc from nativeos/i386-elf-toolchain
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-9.2.0/gcc-9.2.0.tar.xz
Already downloaded: /Users/marcodotio/Library/Caches/Homebrew/downloads/407625276c0d5a542b30f676b4858e6dbbc47bc3ec0cc34094cd8c989bae881d--gcc-9.2.0.tar.xz
==> ../configure --prefix=/opt/homebrew/Cellar/i386-elf-gcc/9.2.0 --target=i386-elf --disable-multilib --disable-nls --disable-werror --without-headers --without-isl --enable-languages=c,c++
==> make all-gcc
Last 15 lines from /Users/marcodotio/Library/Logs/Homebrew/i386-elf-gcc/02.make:
clang++ -no-pie   -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE  -fno-strict-aliasing -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H  -o lto1 \
		lto/lto-lang.o lto/lto.o lto/lto-object.o attribs.o lto/lto-partition.o lto/lto-symtab.o libbackend.a main.o libcommon-target.a libcommon.a ../libcpp/libcpp.a ../libdecnumber/libdecnumber.a  -lmpc -lmpfr -lgmp   -L./../zlib -lz libcommon.a ../libcpp/libcpp.a  -liconv ../libbacktrace/.libs/libbacktrace.a ../libiberty/libiberty.a ../libdecnumber/libdecnumber.a
clang++ -fno-PIE -c  -DIN_GCC_FRONTEND -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE  -fno-strict-aliasing -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -I. -I. -I../../gcc -I../../gcc/. -I../../gcc/../include -I../../gcc/../libcpp/include  -I../../gcc/../libdecnumber -I../../gcc/../libdecnumber/dpd -I../libdecnumber -I../../gcc/../libbacktrace   -o cc1-checksum.o -MT cc1-checksum.o -MMD -MP -MF ./.deps/cc1-checksum.TPo cc1-checksum.c
clang++ -fno-PIE -c  -DIN_GCC_FRONTEND -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE  -fno-strict-aliasing -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -I. -I. -I../../gcc -I../../gcc/. -I../../gcc/../include -I../../gcc/../libcpp/include  -I../../gcc/../libdecnumber -I../../gcc/../libdecnumber/dpd -I../libdecnumber -I../../gcc/../libbacktrace   -o cc1plus-checksum.o -MT cc1plus-checksum.o -MMD -MP -MF ./.deps/cc1plus-checksum.TPo cc1plus-checksum.c
Undefined symbols for architecture arm64:
  "_host_hooks", referenced from:
      gt_pch_save(__sFILE*) in libbackend.a(ggc-common.o)
      gt_pch_restore(__sFILE*) in libbackend.a(ggc-common.o)
      toplev::main(int, char**) in libbackend.a(toplev.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [lto1] Error 1
make[1]: *** Waiting for unfinished jobs....
rm gcc.pod
make: *** [all-gcc] Error 2

**Comment by exgphe** [comment]
The official gcc is not yet compatible with M1. You can find a compatible port of gcc 10 to M1 Mac here https://github.com/iains/gcc-darwin-arm64. The unversioned `brew install gcc` on M1 also installs this port. I don't know if it supports cross-compiling though.
