### ISSUE TITLE
How to use the Timer in timer.c

### ISSUE THREAD

**Issue by zment4** [jdah/tetris-os#66]
Alright, I've been banging my head against the desk for too long now with this. Somebody said they used the timer to wait for a second, and in general it seems very straightforward to do so. 

Just read timer_get() to get ticks, and then loop reading that until enough time passess. The problem I'm having is that what do I setup as the waiting loop? Nothing? I'm not getting it to work.

```cpp
u64 startTicks = timer_get();

while ((timer_get() - startTicks) < ticksToWait);
```

I've tried this and many such variations. It feels like the interrupt is not getting called. I'm initializing the timer with `timer_init();`

Is there something specific I'd need code into the while condition, or specific syntax I need to use? Is it possible the construct possibly gets optimized out by the compiler and that's why it doesn't work?

**Comment by jdah** [comment]
I would try throwing a `panic()` in the timer interrupt, just to check that it's being triggered. Your code should work as written assuming the timer has been initialized properly.

**Comment by zment4** [comment]
> I would try throwing a `panic()` in the timer interrupt, just to check that it's being triggered. Your code should work as written assuming the timer has been initialized properly.
> 
> EDIT: Also I would trust that `gcc` would not throw out a busy loop like that but just in case it is maybe try compiling with `-O0` as well?

Thanks for the optimization pointer. I eventually single stepped the timer_wait function I made, and it optimized the busy-wait loop completely away. I tried using volatile keyword for my internal timer tick variables, but that didn't help, so I went and sprinkled the volatile to _everything_ related - the timer_get() function, the timer state struct, and the timer tick variables I used. It works now!
