### ISSUE TITLE
Error building on windows

### ISSUE THREAD

**Issue by jkrei0** [jdah/tetris-os#7]
I'm trying to build this on windows, and it appears that it can't find `font.o`
I'm rather inexperienced with this type of thing, so I may be misunderstanding the error.

Here's my Command Prompt output:
```
E:\tetris-os>make iso
i386-elf-ld -o ./bin/bootsect.bin src/stage0.o -Ttext 0x7C00 --oformat=binary
i386-elf-gcc -o src/font.o -c src/font.c  -m32 -std=c11 -O2 -g -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wno-pointer-arith -Wno-unused-parameter -nostdlib -nostdinc -ffreestanding -fno-pie -fno-stack-protector -fno-builtin-function -fno-builtin
i386-elf-gcc: error: spawn: No such file or directory
make: *** [Makefile:38: src/font.o] Error 1

E:\tetris-os>
```

**Comment by marchellodev** [comment]
I would suggest to try building with WSL

**Comment by Bigsby** [comment]
You need a cross-compiler, don't you?

**Comment by Bigsby** [comment]
Using a docker image is not a bad idea. 
https://github.com/jornedesmedt/crosscompile-i686-elf

**Comment by jkrei0** [comment]
I have an elf-i686/i386 cross-compiler (I had a different error where it was complaining about not having the cross-compiler), so I wouldn't think that's the issue. I do have WSL, so I'll try building with it and see how it goes.

**Comment by jdah** [comment]
Yeah, sorry, please use WSL for this. Not planning on adding in Windows support in the Makefile.
